name: Code Quality Check

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify your Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Auto-format with Prettier
        run: npx prettier --write .

      - name: Run Linters
        run: npm run lint
