name: Code Quality Check into Develop Branch

on:
  pull_request:
    branches: [develop]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Ceck Prettier Formatting
        run: npx prettier --check .

      - name: Run ESLint
        run: npm run lint
